#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname display_4607 -pa ebin -mnesia debug verbose
main([Filename]) ->
    try
        Bin = s4607:read_file(Filename),
        PacketList = s4607:decode(Bin),
        s4607:display_packets(PacketList)
    catch
        _:_ ->
            usage()
    end;
main(_) ->
    usage().

usage() ->
    io:format("usage: display_4607 filename\n"),
    halt(1).

