#######################################################################
# Makefile for compiling erlang files                                 #
#######################################################################
# code to compile
SOURCE = \
	s4607.erl \
	stanag_types.erl

#Where include files are stored ".hrl"
EFLAGS = -I../include 

#Include following generic make script
include Makefile.inc
